import VBXCore
import SwiftUI

/// What vbx is, and the licences it is obliged to ship.
///
/// The engine links 66 Go modules. Most want their notice carried; a few want
/// more, and beads_viewer's rider must travel **unmodified** in any
/// distribution, with breach terminating the licence to the engine vbx is built
/// on. The default About panel shows a name and a version and none of that.
///
/// The text is generated by `scripts/build-notices.py` and committed, for the
/// same reason as the app icon: regenerating needs a populated Go module cache
/// and `build-app.sh` has to work on a bare clone. `--check` in the verify block
/// keeps the committed copy honest against `go.mod`.
public struct AboutView: View {
    public init() {}

    public var body: some View {
        VStack(spacing: 0) {
            header
            Divider()
            notices
        }
        .frame(minWidth: 520, idealWidth: 620, minHeight: 420, idealHeight: 560)
    }

    private var header: some View {
        HStack(alignment: .top, spacing: 16) {
            if let icon = NSImage(named: "NSApplicationIcon") {
                Image(nsImage: icon)
                    .resizable()
                    .frame(width: 64, height: 64)
            }

            VStack(alignment: .leading, spacing: 3) {
                Text(Self.applicationName)
                    .font(.title2.weight(.semibold))
                let version = Self.versionLine
                if !version.isEmpty {
                    Text(version)
                        .font(.callout)
                        .foregroundStyle(.secondary)
                        .monospacedDigit()
                }
                Text("MIT with the AI Training Rider. Its full text is below.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .padding(.top, 2)
            }
            Spacer(minLength: 0)
        }
        .padding(18)
    }

    private var notices: some View {
        ScrollView {
            Text(Self.acknowledgements)
                .font(.system(.caption, design: .monospaced))
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(16)
        }
    }

    /// The display name from the bundle, never a literal: a literal drifts
    /// against `build-app.sh`, which is where the real one is written.
    static var applicationName: String {
        let info = Bundle.main.infoDictionary
        return info?["CFBundleDisplayName"] as? String
            ?? info?["CFBundleName"] as? String
            ?? "Visual Beads"
    }

    /// What the About box says the build is, e.g. `Version 0.0.1 (42)`.
    ///
    /// The marketing version comes from the git tag and the build number from
    /// the commit count, stamped into the plist by `build-app.sh` — see
    /// `scripts/version.sh` for why neither is written down anywhere else.
    ///
    /// Empty when the keys are absent, which is not a hypothetical: in a test
    /// process `Bundle.main` is SwiftPM's helper binary and both keys are nil.
    /// Absent rather than a placeholder, for the reason the whole codebase
    /// prefers absent to zero — `Version 0.0.0 (0)` would be a claim, and a
    /// wrong one. The header omits the line entirely rather than reserving a
    /// blank row for it.
    static func versionLine(from info: [String: Any]?) -> String {
        let short = info?["CFBundleShortVersionString"] as? String
        let build = info?["CFBundleVersion"] as? String
        switch (short, build) {
        case let (version?, build?): return "Version \(version) (\(build))"
        case let (version?, nil): return "Version \(version)"
        // A build number with no marketing version says nothing a user can
        // use, so it is not shown on its own.
        default: return ""
        }
    }

    /// - Parameter info: injected so the formatting can be tested. The default
    ///   is the real bundle, and a test process never has one — which is
    ///   exactly why this had no coverage until it was made injectable.
    static var versionLine: String { versionLine(from: Bundle.main.infoDictionary) }

    /// The generated notices, read from the bundle.
    ///
    /// A missing file says so rather than showing an empty pane: the
    /// obligation is to *display* these, so silence would be the one failure
    /// mode worth shouting about.
    static var acknowledgements: String {
        guard
            let url = Bundle.main.url(forResource: "ACKNOWLEDGEMENTS", withExtension: "md"),
            let text = try? String(contentsOf: url, encoding: .utf8)
        else {
            return """
                The third-party licence notices could not be loaded from this build.

                They are generated by scripts/build-notices.py into
                Resources/ACKNOWLEDGEMENTS.md and must be bundled with the app.
                """
        }
        return text
    }
}
