#!/usr/bin/env python3
"""Generates docs/RELEASES.md from the annotated git tags.

    python3 scripts/release-notes.py            # regenerate the file
    python3 scripts/release-notes.py --check    # fail if it is out of date

Why the tags and not the log
----------------------------

Grouping releases into features and fixes needs a signal, and this repository's
commit subjects deliberately do not carry one. They are prose:

    Hand the priority cell its store, so scrolling the list cannot crash (#29)
    Load recipes when a workspace opens (#30)

A ``feat:``/``fix:`` parser would classify every one of them as neither. So the
signal comes from the PR's ``semver:*`` label, which is read once — by
``version-bump.sh``, at the moment the tag is created, when ``gh`` is available
— and written into the annotated tag's message:

    vbx 0.2.0

    Change: minor: Load recipes when a workspace opens (#30)
    Change: patch: Hand the priority cell its store (#29)

Everything downstream then reads git alone. That is what lets ``--check`` join
the verify block: it needs no network, no GitHub, and no ordering assumption
beyond the tags themselves.

This file is the *user-facing* view and must not become a fourth copy of what
the repo already records. ``docs/project_notes/BUGS.md`` keeps a bug and the
regression test locking it in; ``docs/project_notes/WORK_LOG.md`` keeps dated
engineering work. Neither is what someone upgrading the app wants to read.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "RELEASES.md"

# minor and major are things you gained; patch is something that stopped being
# wrong. Two headings, because a longer taxonomy is a taxonomy nobody applies
# consistently.
HEADING = {"major": "Features", "minor": "Features", "patch": "Fixes"}
ORDER = ["Features", "Fixes"]

CHANGE = re.compile(r"^Change:\s*(major|minor|patch):\s*(.+?)\s*$")
PR = re.compile(r"\(#(\d+)\)\s*$")

HEADER = """# Releases

What changed for someone using Visual Beads, newest release first.

**Generated by `scripts/release-notes.py` from the annotated git tags — do not
edit.** The engineering-facing views live elsewhere:
[BUGS.md](project_notes/BUGS.md) records a bug and the regression test locking
it in, and [WORK_LOG.md](project_notes/WORK_LOG.md) records dated work.
"""

EMPTY = """
No releases yet. `scripts/version-bump.sh` cuts the first one; until then every
build reports `0.0.0`, which sorts below any real tag.
"""


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True)
    return result.stdout


def repo_url() -> str:
    """The https form of the origin remote, for linking PR numbers."""
    try:
        remote = git("remote", "get-url", "origin").strip()
    except subprocess.CalledProcessError:
        return ""
    remote = re.sub(r"^git@github\.com:", "https://github.com/", remote)
    return re.sub(r"\.git$", "", remote)


def releases() -> list[tuple[str, str, list[tuple[str, str]]]]:
    """Every release tag, newest first, as (version, date, [(heading, text)])."""
    # Sorted by version rather than by date: a tag can be created out of order,
    # and what a reader wants is the version sequence.
    raw = git("tag", "-l", "v[0-9]*", "--sort=-v:refname",
              "--format=%(refname:short)%09%(creatordate:short)")
    found = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        tag, _, date = line.partition("\t")
        message = git("tag", "-l", tag, "--format=%(contents)")
        changes = []
        for entry in message.splitlines():
            match = CHANGE.match(entry)
            if match:
                changes.append((HEADING[match.group(1)], match.group(2)))
        found.append((tag.removeprefix("v"), date.strip(), changes))
    return found


def render() -> str:
    base = repo_url()
    found = releases()
    if not found:
        return HEADER + EMPTY

    lines = [HEADER]
    for version, date, changes in found:
        lines.append(f"\n## {version} — {date}\n")
        if not changes:
            # A tag with no Change lines is a tag made by hand. Saying so beats
            # rendering an empty section that reads as "nothing changed".
            lines.append("\nNo recorded changes — this tag was not cut by "
                         "`scripts/version-bump.sh`.\n")
            continue
        for heading in ORDER:
            entries = [text for group, text in changes if group == heading]
            if not entries:
                continue
            lines.append(f"\n### {heading}\n")
            for text in entries:
                match = PR.search(text)
                if match and base:
                    number = match.group(1)
                    text = PR.sub(f"([#{number}]({base}/pull/{number}))", text)
                lines.append(f"\n- {text}")
            lines.append("\n")
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed file is out of date")
    args = parser.parse_args()

    generated = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != generated:
            print("docs/RELEASES.md is out of date; run "
                  "python3 scripts/release-notes.py", file=sys.stderr)
            return 1
        count = len(releases())
        print(f"==> release notes check ok ({count} release"
              f"{'' if count == 1 else 's'})")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated)
    print(f"==> wrote {OUT.relative_to(ROOT)} ({len(releases())} releases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
